#Servizi necessari a realizzare un applicazione simile a ticketone
services:
  app:
    image: nginx:alpine
    ports:
      - "80:80" #porta 80 del container mappata alla porta 80 del host
    volumes:
      - ./app:/usr/share/nginx/html #cartella app del progetto mappata alla cartella html del container
    depends_on:
      - api 
  api:
    build: ./api
    ports:
      - "3000:3000" #porta 3000 del container mappata alla porta 3000 del host
    volumes:
      - ./api:/usr/src/app #cartella api del progetto mappata alla cartella app del container
    depends_on:
      - db
  db:
    image: mysql:5.7
    ports:
      - "3306:3306" #porta 3306 del container mappata alla porta 3306 del host
    volumes:
      - ./db:/var/lib/mysql #cartella db del progetto mappata alla cartella mysql del container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ticketone
      MYSQL_USER: ticketone
      MYSQL_PASSWORD: ticketone
  backend:
    build: ./backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: development
    command: flask run --host=0.0.0.0
  frontend:
    build: ./frontend
    restart: always
    ports:
      - "3000:3000"
    environment:
      API_URL: http://backend:5000/api
    command: npm run dev